# advent 9. Movie Theater

In [1]:
with open("day9_tst.txt", 'r') as f:
        content = f.read().split("\n")
content

inputLocs = []
for r in content:
    startx, endx = map(int, r.split(","))
    inputLocs.append([startx, endx])

#print(inputLocs)

In [ ]:
import numpy as np


data = np.loadtxt('day9_ex.txt', delimiter=',')
col0 = data[:, 0].astype(int)
col1 = data[:, 1].astype(int)

points = np.column_stack((col0, col1))
max_r = points[:,0].max() + 1
max_c = points[:,1].max() + 1

D = np.zeros((max_r, max_c), dtype=np.uint8)

for i in range(len(points)):
    r1, c1 = points[i]
    r2, c2 = points[(i+1) % len(points)]

    # vertical edge
    if c1 == c2:
        rmin, rmax = sorted([r1, r2])
        D[rmin:rmax+1, c1] = 1

    # horizontal edge
    elif r1 == r2:
        cmin, cmax = sorted([c1, c2])
        D[r1, cmin:cmax+1] = 1

    # no diagonal edges in your example
for r in range(D.shape[0]):
    cols = np.where(D[r] == 1)[0]
    if len(cols) < 2:
        continue

    # fill between every pair of crossings
    for i in range(0, len(cols)-1, 2):
        c_start = cols[i]
        c_end   = cols[i+1]
        D[r, c_start:c_end+1] = 1

In [ ]:
# points = np.array([
#     [7,1],
#     [11,1],
#     [11,7],
#     [9,7],
#     [9,5],
#     [2,5],
#     [2,3],
#     [7,3]
# ])

N = len(points)
best_score = np.zeros(N, dtype=int)

for i in range(N):
    r1, c1 = points[i]

    for j in range(i+1, N):
        r2, c2 = points[j]

        # Must differ in both row and column
        if r1 == r2 or c1 == c2:
            continue

        # Bounding box
        rmin, rmax = sorted([r1, r2])
        cmin, cmax = sorted([c1, c2])

        rect = D[rmin:rmax+1, cmin:cmax+1]

        # Skip if any zero inside
        if np.any(rect == 0):
            continue

        # Score = number of 1s inside
        score = np.sum(rect)

        # Update best score for both points
        if score > best_score[i]:
            best_score[i] = score
        if score > best_score[j]:
            best_score[j] = score

print(max(best_score))

24


In [33]:
import numpy as np
import math
data = np.loadtxt('day9_ex.txt',delimiter=',')
col0 = data[:, 0].astype(int)
col1 = data[:, 1].astype(int)
#print(col0)
#print(col1)

# print(np.max(col0))
# print(np.max(col1))

# print(np.min(col0))
# print(np.min(col1))

D = np.zeros((int(np.max(col0))+1, int(np.max(col1))+1),dtype=np.int8)
D[col0,col1] = 2

# --- Fill between 2s (rows) ---
for r in range(D.shape[0]):
    cols = np.where(D[r] == 2)[0]
    if len(cols) >= 2:
        D[r, cols[0]:cols[-1]+1] = 1
        D[r, cols] = 2

# --- Fill between 2s (columns) ---
for c in range(D.shape[1]):
    rows = np.where(D[:, c] == 2)[0]
    if len(rows) >= 2:
        D[rows[0]:rows[-1]+1, c] = 1
        D[rows, c] = 2

# --- Fill between 1s (rows) ---
for r in range(D.shape[0]):
    cols = np.where(D[r] == 1)[0]
    if len(cols) >= 2:
        D[r, cols[0]:cols[-1]+1] = 1

# --- Fill between 1s (columns) ---
for c in range(D.shape[1]):
    rows = np.where(D[:, c] == 1)[0]
    if len(rows) >= 2:
        D[rows[0]:rows[-1]+1, c] = 1

print(D)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 2 1 2 0 0]
 [0 0 0 1 1 1 0 0]
 [0 0 0 1 1 1 0 0]
 [0 0 0 1 1 1 0 0]
 [0 0 0 1 1 1 0 0]
 [0 2 1 1 1 1 0 0]
 [0 1 1 1 1 1 0 0]
 [0 1 1 1 1 1 1 2]
 [0 1 1 1 1 1 1 1]
 [0 2 1 1 1 1 1 2]]


In [37]:
points = np.column_stack((col0, col1))
num_points = len(points)

best_score = np.zeros(num_points, dtype=int)

for i in range(num_points):
    r1, c1 = points[i]

    for j in range(i+1, num_points):
        r2, c2 = points[j]

        # Check square condition
        if abs(r1 - r2) != abs(c1 - c2):
            continue

        # Bounding box
        rmin, rmax = sorted([r1, r2])
        cmin, cmax = sorted([c1, c2])

        square = D[rmin:rmax+1, cmin:cmax+1]

        # Skip if any zero
        if np.any(square == 0):
            continue

        # Score = ones inside + 2 for the corners
        ones_inside = np.sum(square == 1)
        score = ones_inside + 2

        # Update best score for both points
        if score > best_score[i]:
            best_score[i] = score
        if score > best_score[j]:
            best_score[j] = score

print(best_score)

[ 0  0  9  0 11  0  0 11]


In [25]:
Loc1 = inputLocs[0]
Loc2 = inputLocs[1]

xdif = abs(Loc1[0] - Loc2[0]) +1
ydif = abs(Loc1[1] - Loc2[1]) +1


In [26]:
def findareaBetweenCorners(L1, L2):
    xdif = abs(L1[0] - L2[0]) +1
    ydif = abs(L1[1] - L2[1]) +1
    multi = xdif * ydif
    return multi

In [27]:
N = len(inputLocs)
maxArea = 0
for ii in range(N):
    Loc1 = inputLocs[ii]
    for jj in range(N):
        if ii!=jj:
            Loc2 = inputLocs[jj]
            miijj = findareaBetweenCorners(Loc1, Loc2)
            if miijj > maxArea:
                maxArea = miijj
            #print(f"for L1 = {Loc1}, L2 = {Loc2}, area is {miijj}")
print(maxArea)

4750176210
