# Day 8. Playground part 1.

In [17]:
import numpy as np
data = np.loadtxt('day8_ex.txt',delimiter=',')
print(data)

N = len(data)
#D= np.zeros((N,N))
D = np.full((N, N), np.nan)
for ni in range(N):
    for di in range(N):
        #d = 0
        if  ni != di and di > ni:
            D[ni,di] = np.linalg.norm(data[ni,:]-data[di,:])
        #print(f"ni = {data[ni,:]}, di = {data[di,:]}, dist = {d}")
        #print(f"ni = {ni}, di = {di}")
#D = np.linalg.norm(data-data)
print(D)


[[162. 817. 812.]
 [ 57. 618.  57.]
 [906. 360. 560.]
 [592. 479. 940.]
 [352. 342. 300.]
 [466. 668. 158.]
 [542.  29. 236.]
 [431. 825. 988.]
 [739. 650. 466.]
 [ 52. 470. 668.]
 [216. 146. 977.]
 [819. 987.  18.]
 [117. 168. 530.]
 [805.  96. 715.]
 [346. 949. 466.]
 [970. 615.  88.]
 [941. 993. 340.]
 [862.  61.  35.]
 [984.  92. 344.]
 [425. 690. 689.]]
[[          nan  787.81406436  908.78435286  561.71879086  723.78795237
   736.43261742 1047.43496218  321.56025874  693.20559721  391.46519641
   693.09595295 1044.50227381  709.04865841  970.92687675  413.51662603
  1103.55969481  927.68583044 1290.45147139 1191.77724429  316.90219311]
 [          nan           nan 1019.98725482 1041.7461303   471.43398265
   424.24285498  783.70083578 1024.44423958  795.88252902  628.68911236
  1046.1668127   847.54114944  655.61345319 1124.70084911  600.30242378
   913.53106132 1001.08441203  979.16188651 1103.79980069  734.86869575]
 [          nan           nan           nan  507.10649769  61

In [33]:
min_value = np.nanmin(D)
flat_min = np.nanargmin(D)
index_2d = np.unravel_index(flat_min, D.shape)
groups = []
for rep in range(10):
    pair = list(index_2d) 
    if not groups:
       groups.append(pair) 
    else:
        for gi in groups:
            flat = {x for p in gi for x in p}

            # Match if ANY element overlaps
            if pair[0] in flat or pair[1] in flat:
                gi.append(pair)
                placed = True
                break

        if not placed:
            groups.append([pair])
#if elements in list(index_2d) in gi, add them to gi.
            # Check all the elements, of groups. 
            # If list(index_2D) not in any of groups. start a new list and add it to groups 
print(groups)

TypeError: 'numpy.int64' object is not iterable

In [26]:
D[0,19] = np.nan
flat_min = np.nanargmin(D)
index_2d = np.unravel_index(flat_min, D.shape)
print(min_value)
print(f"flatmin is {flat_min}, idx2D is {index_2d}")

316.90219311326956
flatmin is 7, idx2D is (np.int64(0), np.int64(7))
